profile: null
region: ap-northeast-1
versioning: false
default_alias: null
configuration:
  name: ci-lambda-ucs4
  runtime: python2.7
  role: arn:aws:iam::713403314913:role/lambda_exec_role
  handler: lambda_function.lambda_handler
  description: test usc4 upload from CircleCI
  timeout: 10
  memory_size: 128
  vpc_config:
    subnets:
    security_groups:
